import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
FRONTEND_URL = os.getenv("FRONTEND_URL")

print("CLIENT_ID =", GOOGLE_CLIENT_ID)
print("CLIENT_SECRET =", GOOGLE_CLIENT_SECRET)
print("REDIRECT_URI =", GOOGLE_REDIRECT_URI)
print("FRONTEND_URL =", FRONTEND_URL)